"""change_amount_to_numeric

Revision ID: 7b8b941a2c35
Revises: a50c75fe3e2c
Create Date: 2026-05-16 21:36:46.250742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b8b941a2c35'
down_revision: Union[str, Sequence[str], None] = 'a50c75fe3e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('billings', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('reconciliations', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reconciliations', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('billings', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###
